---
name: ServerSwitcher
description: a plugin adds a simple server switching command to your server allowing players to quickly switch between different servers on the network
version: 1.0
author: iMD14
website: https://bukkitteam.letz.dev

main: iMD14\ServerSwitcher\Main
api: 5.1.2
src-namespace-prefix: iMD14\ServerSwitcher

commands:
  server:
    description: Transfers you to a target server
    permission: serverswitcher.use
permissions:
  serverswitcher.use:
    default: true
...
